### PR TITLE
Added synchronization map in languageservice

### PR DESCRIPTION
**Pull request by shivasin-ms**

### CODE REVIEW

**Comment by gundermanc** [comment]
I'm seeing errors when building: 

> Severity	Code	Description	Project	File	Line	Suppression State
Error		..\languageservice\workspace.go:19:36: too few values in workspaceManager literal	Go.Interop	C:\repos\vs-go\src\Go.Interop\Go.Interop.csproj	25

**Comment by gundermanc** [comment]
Note that the CI doesn't currently build the Go portion.

**Comment by shivasin-ms** [comment]
The same error I was seeing before adding my changes, let me check if something is missing in the declaration if this struct.

Thanks,
Shivam Singh

Microsoft Intune

[microsoft]

**Comment by shivasin-ms** [comment]
I missed this thing, fixed it now.

**Pull request merged**
